version: '3'

services:
  postgres:
    container_name: mba-marketplace-postgres
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mba-marketplace
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres


