version: '3'

services:
  postgres:
    container_name: mba-marketplace-postgres
    image: postgres
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mba-marketplace
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  redis:
    container_name: mba-marketplace-redis
    image: redis
    ports:
      - 6378:6379
    volumes:
      - ./data/redis:/data